Repository aivle-farmpedia/backend, pull requests merged in 2024-06, with the labels that each got.

#3 feat : uuid 기능 추가 및 로깅 구성 추가
  src/main/java/com/farm/pedia/FarmPediaApplication.java
  src/main/java/com/farm/pedia/user/controller/UserController.java
  src/main/java/com/farm/pedia/user/domain/User.java
  src/main/java/com/farm/pedia/user/dto/UserSaveRequest.java
  src/main/java/com/farm/pedia/user/mapper/UserMapper.java
  src/main/java/com/farm/pedia/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/mappers/user/UserMapper.xml
Labels: feature

#6 chore : CI/CD 설정
  .github/workflows/gradle.yml
  build.gradle.kts
Labels: infra

#8 refact : 사용하지 않는 API 제거 및 컨트롤러 이동
  src/main/java/com/farm/pedia/auth/controller/AuthController.java
  src/main/java/com/farm/pedia/user/controller/UserController.java
  src/main/java/com/farm/pedia/user/service/UserService.java
Labels: refactor

#13 feat : 검색어 기능
  build.gradle.kts
  src/main/java/com/farm/pedia/config/RedisConfig.java
  src/main/java/com/farm/pedia/global/config/CorsFilter.java
  src/main/java/com/farm/pedia/global/config/WebMvcConfig.java
  src/main/java/com/farm/pedia/searchHistory/controller/SearchHistoryController.java
  src/main/java/com/farm/pedia/searchHistory/domain/SearchHistory.java
  src/main/java/com/farm/pedia/searchHistory/mapper/SearchHistoryMapper.java
  src/main/java/com/farm/pedia/searchHistory/service/SearchHistoryService.java
  src/main/resources/application.yml
  src/main/resources/mappers/searchHistory/SearchHistoryMapper.xml
  src/main/resources/redis-server.yml
Labels: feature

#16 Feature/#15 예외 핸들러 추가
  src/main/java/com/farm/pedia/board/domain/Board.java
  src/main/java/com/farm/pedia/board/exception/BoardExceptionHandler.java
  src/main/java/com/farm/pedia/board/exception/exceptions/BoardAlreadyDeletedException.java
  src/main/java/com/farm/pedia/board/exception/exceptions/BoardAuthorOnlyException.java
  src/main/java/com/farm/pedia/board/exception/exceptions/BoardNotFoundException.java
  src/main/java/com/farm/pedia/board/service/BoardService.java
  src/main/java/com/farm/pedia/comment/domain/Comment.java
  src/main/java/com/farm/pedia/comment/exception/CommentExceptionHandler.java
  src/main/java/com/farm/pedia/comment/exception/exceptions/CommentAlreadyDeletedException.java
  src/main/java/com/farm/pedia/comment/exception/exceptions/CommentAuthorOnlyException.java
  src/main/java/com/farm/pedia/comment/exception/exceptions/CommentNotFoundException.java
  src/main/java/com/farm/pedia/comment/service/CommentService.java
  src/main/java/com/farm/pedia/global/config/RedisConfig.java
  src/main/java/com/farm/pedia/global/exception/AbstractExceptionHandler.java
  src/main/java/com/farm/pedia/user/exception/UserExceptionHandler.java
  src/main/java/com/farm/pedia/user/exception/exceptions/UserNotFoundException.java
  src/main/java/com/farm/pedia/user/service/UserService.java
Labels: feature

#19 refact : 게시글 카테고리 삭제
  src/main/java/com/farm/pedia/board/domain/Board.java
  src/main/java/com/farm/pedia/board/dto/request/BoardCreateRequest.java
  src/main/java/com/farm/pedia/board/dto/request/BoardUpdateRequest.java
  src/main/java/com/farm/pedia/board/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: refactor

#20 chore : CI/CD 설정
  .github/workflows/gradle.yml
Labels: infra

#22 Feature/#21 지원 정책
  build.gradle.kts
  src/main/java/com/farm/pedia/global/dto/response/PagedResponse.java
  src/main/java/com/farm/pedia/supportPolicy/controller/SupportPolicyController.java
  src/main/java/com/farm/pedia/supportPolicy/domain/SimpleSupportPolicy.java
  src/main/java/com/farm/pedia/supportPolicy/domain/SupportPolicy.java
  src/main/java/com/farm/pedia/supportPolicy/dto/response/SupportPolicyResponse.java
  src/main/java/com/farm/pedia/supportPolicy/mapper/SupportPolicyMapper.java
  src/main/java/com/farm/pedia/supportPolicy/service/SupportPolicyService.java
  src/main/resources/mappers/supportPolicy/SupportPolicy.xml
Labels: feature

#24 Feature/#23 페이징 커스텀
  src/main/java/com/farm/pedia/board/controller/BoardController.java
  src/main/java/com/farm/pedia/board/dto/response/BoardsResponse.java
  src/main/java/com/farm/pedia/board/mapper/BoardMapper.java
  src/main/java/com/farm/pedia/board/service/BoardService.java
  src/main/java/com/farm/pedia/comment/controller/CommentController.java
  src/main/java/com/farm/pedia/comment/dto/response/CommentsResponse.java
  src/main/java/com/farm/pedia/comment/mapper/CommentMapper.java
  src/main/java/com/farm/pedia/comment/service/CommentService.java
  src/main/resources/mappers/board/BoardMapper.xml
  src/main/resources/mappers/comment/CommentMapper.xml
Labels: feature

#25 refact : 불필요한 import문 제거
  src/main/java/com/farm/pedia/supportPolicy/service/SupportPolicyService.java
Labels: refactor

#27 Feature/#26 작성자 판단
  src/main/java/com/farm/pedia/auth/controller/AuthController.java
  src/main/java/com/farm/pedia/auth/dto/request/UserSaveRequest.java
  src/main/java/com/farm/pedia/auth/dto/response/UserSaveResponse.java
  src/main/java/com/farm/pedia/board/dto/response/BoardReadResponse.java
  src/main/java/com/farm/pedia/board/dto/response/BoardWriteResponse.java
  src/main/resources/mappers/board/BoardMapper.xml
  src/main/resources/mappers/supportPolicy/SupportPolicy.xml
Labels: feature

#29 Feature/#28 작물 정보
  src/main/java/com/farm/pedia/crop/controller/CropController.java
  src/main/java/com/farm/pedia/crop/domain/Crop.java
  src/main/java/com/farm/pedia/crop/domain/CropDetails.java
  src/main/java/com/farm/pedia/crop/domain/CropProcess.java
  src/main/java/com/farm/pedia/crop/domain/PriceEntry.java
  src/main/java/com/farm/pedia/crop/domain/Variety.java
  src/main/java/com/farm/pedia/crop/mapper/CropMapper.java
  src/main/java/com/farm/pedia/crop/service/CropService.java
  src/main/resources/mappers/crop/CropMapper.xml
Labels: feature

#33 Hotfix/#32 댓글 수정
  src/main/java/com/farm/pedia/comment/exception/CommentExceptionHandler.java
  src/main/resources/mappers/comment/CommentMapper.xml
Labels: hotfix

#30 feat : 기존 검색어 저장 기능 수정 및 연관검색어 기능 추가
  src/main/java/com/farm/pedia/global/exception/AbstractExceptionHandler.java
  src/main/java/com/farm/pedia/global/exception/CustomExceptionHandler.java
  src/main/java/com/farm/pedia/searchHistory/controller/SearchHistoryController.java
  src/main/java/com/farm/pedia/searchHistory/domain/SearchResults.java
  src/main/java/com/farm/pedia/searchHistory/mapper/SearchHistoryMapper.java
  src/main/java/com/farm/pedia/searchHistory/service/SearchHistoryService.java
  src/main/java/com/farm/pedia/searchHistory/service/impl/SearchHistoryServiceImpl.java
  src/main/resources/mappers/searchHistory/SearchHistoryMapper.xml
Labels: feature

#39 fix : 검색어 저장 기능 수정
  src/main/java/com/farm/pedia/searchHistory/controller/SearchHistoryController.java
  src/main/java/com/farm/pedia/searchHistory/service/impl/SearchHistoryServiceImpl.java
  src/main/resources/mappers/searchHistory/SearchHistoryMapper.xml
Labels: feature
